[package]
name = "jwerle/base64-wasm"
version = "0.1.3"
description = "A base64 implementation written in ZZ compiled to WASM"
license = "MIT"
repository = "jwerle/base64-wasm"

[[module]]
name = "base64"
source = "base64.wasm"
