[package]
name = "jwerle/base64-wasm"
version = "0.1.6"
description = "A base64 implementation written in ZZ compiled to WASM"
license = "MIT"
repository = "little-core-labs/base64-wasm"
readme = "README.md"
homepage = "https://github.com/little-core-labs/base64-wasm"

[[module]]
name = "base64"
source = "base64.wasm"
